# Generated by Django 4.0.6 on 2022-07-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.FileField(upload_to='cases/', verbose_name='дело')),
            ],
            options={
                'verbose_name': 'кейс',
                'verbose_name_plural': 'кейсы',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('photo', models.ImageField(upload_to='clients/', verbose_name='фото')),
                ('review', models.CharField(max_length=300, verbose_name='отзыв')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('phone_number', models.IntegerField(verbose_name='номер')),
                ('request', models.CharField(max_length=500, verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя')),
                ('photo', models.ImageField(upload_to='services/', verbose_name='фото')),
                ('description', models.CharField(max_length=1000, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'сервис',
                'verbose_name_plural': 'сервисы',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('photo', models.ImageField(upload_to='workers/', verbose_name='фото')),
                ('work_experience', models.IntegerField(verbose_name='стаж')),
                ('description', models.CharField(max_length=300, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
            },
        ),
    ]
